#!/usr/bin/env bash
# Regenerates deploy/nginx/cloudflare-real-ip.conf from Cloudflare's published
# edge ranges (https://www.cloudflare.com/ips/). Run when Cloudflare announces
# range changes (rare), commit, push — the sync-host workflow ships it to the
# host. The security group picks the same ranges up live from cloudflare.com
# on the next `terraform apply`, so both layers stay in step.
set -euo pipefail
cd "$(dirname "$0")/.."
out=deploy/nginx/cloudflare-real-ip.conf

{
  echo "# Generated by scripts/update-cloudflare-ips.sh — do not edit by hand."
  echo "# Trust CF-Connecting-IP only for connections that arrive FROM a Cloudflare"
  echo "# edge; anything connecting directly keeps its socket address as \$remote_addr,"
  echo "# so the header cannot be spoofed around the admin allowlist."
  for u in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    # `|| [ -n "$range" ]` keeps the final line even without a trailing newline.
    curl -fsS "$u" | while read -r range || [ -n "$range" ]; do
      [ -n "$range" ] && echo "set_real_ip_from $range;"
    done
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$out"

echo "wrote $out:"
grep -c set_real_ip_from "$out"
